apiVersion: app.tuff.local/v1alpha1
kind: TuffMongo
metadata:
  name: tuffmongo-v1
spec:
   mongoReplicas: 1
   mongoImage: image-registry.openshift-image-registry.svc:5000/tuff/mongo:4.2.23-bionic
   mongoContainerName: mongodb-container
   mongoPorts:
      - name: mongodb
        protocol: TCP
        containerPort: 27017
        hostPort: 27107 
   mongoVolumeMounts:
      - mountPath: /data/db
        name: mongodb-data
      - mountPath: /data/configdb
        name: mongodb-config
   mongoVolumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-data
      - persistentVolumeClaim:
           claimName: mongodb-pvc-config
        name: mongodb-config

