---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.tuff.local
  resources:
  - tuffmongoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.tuff.local
  resources:
  - tuffmongoes/finalizers
  verbs:
  - update
- apiGroups:
  - app.tuff.local
  resources:
  - tuffmongoes/status
  verbs:
  - get
  - patch
  - update
